
services:
  # This is the new service for your React Frontend App
  frontend:
    build:
      context: ../
      dockerfile: apps/shell/Dockerfile
    restart: always
    # We don't need to expose ports here because the nginx-proxy will handle it

  # This is the main Nginx Proxy that routes traffic
  nginx-proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    restart: always
    depends_on:
      - frontend
      - directus

  # The Directus service remains mostly the same
  directus:
    image: directus/directus:latest
    user: "1000:1000"
    env_file: .env
    environment:
      CORS_ENABLED: "true"
      CORS_ORIGIN: "https://wade-usa.com,https://www.wade-usa.com"
      # ... other env variables
    restart: always
    depends_on:
      - db

  # The DB and Certbot services remain the same
  db:
    image: postgres:15-alpine
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt