
services:
  # This is the service for your React Frontend App
  frontend:
    build:
      context: ../
      dockerfile: apps/shell/Dockerfile
    restart: always

  # This is the main Nginx Proxy that routes traffic
  nginx-proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    restart: always
    depends_on:
      - frontend
      - directus

  # Directus service
  directus:
    image: directus/directus:latest
    user: "1000:1000"
    env_file: .env
    environment:
      CORS_ENABLED: "true"
      CORS_ORIGIN: "https://wade-usa.com,https://www.wade-usa.com,http://localhost:5173"
      KEY: ${KEY}
      SECRET: ${SECRET}
      PUBLIC_URL: "https://api.wade-usa.com"
      DB_CLIENT: 'pg'
      DB_HOST: 'db'
      DB_PORT: '5432'
      DB_DATABASE: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    depends_on:
      - db
    restart: always

  # Database service
  db:
    image: postgres:15-alpine
    volumes:
      # This now uses a Docker-managed named volume for data safety.
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always

  # Certbot service
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

# This new section at the very end defines the named volume.
volumes:
  db_data: