server {
    listen 80; # Nginx inside this container listens on port 80

    root /usr/share/nginx/html; # React build output is copied here
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html; # Essential for React Router client-side routing
    }
}