import fs from 'node:fs';


async function dbChecker(db){
    /* ----------------------------- Todo DB Checker ---------------------------- */
    try{
        var date = await db.query("SELECT * FROM public.todo");
        console.log("ToDo DB exists nothing was created");
    }catch(error){
        console.error("Table does not exist creating a new TODO table and will fill with dummy data");
        await db.query("CREATE TABLE todo( id bigint GENERATED BY DEFAULT AS IDENTITY, item text, completed BOOLEAN DEFAULT FALSE)")
        //Dummy Info
        var dummy = [["To Do 1", false],["To Do 2", false],["To Do 3", false], ["To Do 4", true]];
        
        for(let i=0; i < dummy.length; i++){
            db.query("INSERT INTO public.todo ( item, completed) VALUES ($1, $2)", [ dummy[i][0], dummy[i][1]]);
        }
        console.log("ToDo Database Succesfully Created")
    }
    /* ----------------------------- Travel DB Checker ---------------------------- */

    try{
        var travel = await db.query("SELECT * FROM public.travel");
        console.log("Travel DB does exist nothing was created");
    }catch(error){
        console.error("Travel Table Does not exist. Creating a new Travel Table and Filling with Dummy Data")
        await db.query("CREATE TABLE travel( id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tripname text, startdate text, enddate text)")
        const trips = JSON.parse(fs.readFileSync('./connect_to_db/travel.json', "utf-8"));
        const dummy =trips;

        // Use a loop with await inside an async function
        for (const data of dummy) { // Use for...of loop for cleaner async iteration
            await db.query('INSERT INTO travel (tripname, startdate, enddate) VALUES ($1, $2, $3)', data);
        }
        console.log("Travel Database Succesfully Created")
    }

    try{
        var departingflights = await db.query("SELECT * FROM public.departingflights")
        console.log("Departing Flights Do exist nothing was created")
    }catch(error){
        console.error("Departing Flights Table Does not Exist. Creating a new table and filling it with dummy data")
        await db.query("CREATE TABLE departingflights (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, trip_id bigint, date text, origin text, airline text, flight text, depart text, dest text, land text)");        
        const data = JSON.parse(fs.readFileSync('./connect_to_db/depart_flights.json', 'utf-8'))
        const dummy = data;
        for (const item of dummy){
            await db.query("INSERT INTO departingflights (trip_id, date, origin, airline, flight, depart, dest, land) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)",item)
        }
        console.log("Departing Flight Table Successfully Created")
        //console.log(dummy)
    }
    
    try{
        var hotels = await db.query("SELECT * FROM public.hotels")
        console.log("Hotels Do exist nothing was created")
    }catch(error){
        console.error("Hotels Table Does not Exist. Creating a new table and filling it with dummy data")
        await db.query("CREATE TABLE hotels (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, trip_id bigint, checkin text, name text, address text, number text, checkout text)");        
        const data = JSON.parse(fs.readFileSync('./connect_to_db/hotels.json', 'utf-8'))
        const dummy = data;
        for (const item of dummy){
            await db.query("INSERT INTO hotels (trip_id, checkin, name, address, number, checkout) VALUES ($1, $2, $3, $4, $5, $6)",item)
        }
        console.log("Hotels Table Successfully Created")
        //console.log(dummy)
    }

    try{
        var rc = await db.query('SELECT * FROM public.rc')
        console.log("Rental Cars DB Exists Nothing Was Created")
    }catch(error){
        console.error("Rental Cars Table does not exists. Creating a new Table and Filling it with dummy data")
        await db.query('CREATE TABLE rc (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, trip_id bigint, pu text, putime text, company text, location text, return text, returntime text)')
        const data = JSON.parse(fs.readFileSync('./connect_to_db/rc.json', 'utf-8'))
        const dummy = data
        for(const item of dummy){
            await db.query("INSERT INTO rc (trip_id , pu , putime , company , location , return , returntime) VALUES ($1, $2, $3, $4, $5, $6, $7)", item)
        }
        console.log("Rental Cars Table Successfully Created ")
    }

    try{
        var act = await db.query("SELECT * FROM public.activities")
        console.log("Activities Table Exists Nothing Was Created")
    }catch(error){
        console.error("Activites Table does not exists. Creating a new table and filling with dummy data")
        await db.query('CREATE TABLE activities (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, trip_id bigint, date text, time text, event text, details text)')
        const data = JSON.parse(fs.readFileSync('./connect_to_db/activities.json', 'utf-8'))
        const dummy = data
        for(const item of dummy){
            await db.query("INSERT INTO activities (trip_id , date , time , event , details) VALUES ($1, $2, $3, $4, $5)", item)
        }
        console.log("Acvtivies Table Successfully Created ")
    }

    try{
        var departingflights = await db.query("SELECT * FROM public.arrivingflights")
        console.log("Arriving Flights Do exist nothing was created")
    }catch(error){
        console.error("Arriving Flights Table Does not Exist. Creating a new table and filling it with dummy data")
        await db.query("CREATE TABLE arrivingflights (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, trip_id bigint, date text, origin text, airline text, flight text, depart text, dest text, land text)");        
        const data = JSON.parse(fs.readFileSync('./connect_to_db/depart_flights.json', 'utf-8'))
        const dummy = data;
        for (const item of dummy){
            await db.query("INSERT INTO arrivingflights (trip_id, date, origin, airline, flight, depart, dest, land) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)",item)
        }
        console.log("Arriving Flight Table Successfully Created")
        //console.log(dummy)
    }

}

export default dbChecker; 