
async function dbChecker(db){
    /* ----------------------------- Todo DB Checker ---------------------------- */
    try{
        var date = await db.query("SELECT * FROM public.todo");
        console.log("ToDo DB exists nothing was created");
    }catch(error){
        console.error("Table does not exist creating a new TODO table and will fill with dummy data");
        await db.query("CREATE TABLE todo( id bigint GENERATED BY DEFAULT AS IDENTITY, item text, completed BOOLEAN DEFAULT FALSE)")
        //Dummy Info
        var dummy = [["To Do 1", false],["To Do 2", false],["To Do 3", false], ["To Do 4", true]];
        
        for(let i=0; i < dummy.length; i++){
            db.query("INSERT INTO public.todo ( item, completed) VALUES ($1, $2)", [ dummy[i][0], dummy[i][1]]);
        }
        console.log("ToDo Database Succesfully Created")
    }
    /* ----------------------------- Travel DB Checker ---------------------------- */

    try{
        var travel = await db.query("SELECT * FROM public.travel");
        console.log("Travel DB does exist nothing was created");
    }catch(error){
        console.error("Travel Table Does not exist. Creating a new Travel Table and Filling with Dummy Data")
        await db.query("CREATE TABLE travel( id bigint GENERATED BY DEFAULT AS IDENTITY, tripname text, attribute text, detail text)")
        var dummy = [["Thailand 2/5/25","startdate","2/5/25"], ["Trip 2", "startdate", "1/1/25"],
                    ["Thailand 2/5/25","enddate","2/2/25"], ["Trip 2", "enddate", "1/30/25"] ];

        // Use a loop with await inside an async function
        for (const data of dummy) { // Use for...of loop for cleaner async iteration
            await db.query('INSERT INTO travel (tripname, attribute, detail) VALUES ($1, $2, $3)', data);
        }
        console.log("Travel Database Succesfully Created")
    }
    
}

export default dbChecker; 